### PR TITLE
Robot description topic

### PR DESCRIPTION
**Pull request by Timple**
### Description

To ease the transition to ROS2 we would like to use a robot_description topic instead of a parameter. Solves #1694 

### Checklist

- [ ] If you are addressing rendering issues, please provide:
  - [ ] Images of both, broken and fixed renderings.
  - [ ] Source code to reproduce the issue, e.g. a `YAML` or `rosbag` file with a `MarkerArray` msg.
- [x] If you are changing GUI, please include screenshots showing how things looked *before* and *after*.
- [x] Choose the proper target branch: latest release branch, for non-ABI-breaking changes, *future* release branch otherwise.
      Due to the lack of active maintainers, we cannot provide support for older release branches anymore.
- [ ] Did you change how RViz works? Added new functionality? Do not forget to update the tutorials and/or documentation on the [ROS wiki](http://wiki.ros.org/rviz)
- [x] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-visualization/rviz/pulls) to support the maintainers of RViz. Refer to the [RViz Wiki](https://github.com/ros-visualization/rviz/wiki/Maintainer-Guide#reviewing-pull-requests) for reviewing guidelines.

image image

### CODE REVIEW

**Review by rhaschke — COMMENTED** [review]
I am hesitant to merge this as the robot description is handled as a parameter throughout ROS1.
Changing it to a topic requires lots of changes elsewhere as well.
I don't yet see how the availability of the topic parameter facilitates migration to ROS2. Can't you always run rviz2 to have this functionality there?

**Comment by Timple** [comment]
> how the availability of the topic parameter facilitates migration to ROS2.

Well, having it as a topic allows it to pass the `ros1_bridge`. Parameters don't do that. We plan to port our nodes 1-by-1 to the ROS2 side of the bridge.

> requires lots of changes elsewhere

For us not that much actually. `robot_state_publisher` would need to publish (or read) a topic as well. That's on my todo-list.

All places where we now parse a urdf, we simply make a subscription.

> Can't you always run rviz2

Probably, but the bridge is not in place yet on the real robot (risk). We're in the preparation stage. For large projects this could really take a while I'm affraid.

---

But most of all, this allows us to leverage the force of a topic already in ROS1. Because our robot is becoming more-and-more dynamic, we need restarts on changes in the urdf.

**Comment by peci1** [comment]
There have already been several attempts at dynamically changing the robot model. See https://github.com/ros/robot_state_publisher/pull/31 and https://github.com/peci1/dynamic_robot_state_publisher as a workaround until that PR is merged. These approaches use a `Trigger`-type service to force a reload of the parameter (with dynamic_robot_state_publisher also supporting dynamic_reconfigure, which is basically subscription to a topic). Wouldn't adding a `reload_robot_models` service solve this issue? You could then write a simple node that would listen on the model topic and update the param and call the trigger service of rviz and robot_state_publisher.

**Comment by Timple** [comment]
Thank you for pointing me in this direction and thinking along!

From the activity, it doesn't look like https://github.com/ros/robot_state_publisher/pull/31 is going to be merged any sooner than this.

But my rationale of using a topic is to align already with ROS2. They probably (assumption here) thought about deeply and deemed a topic the right solution.
For me this also makes sense: it can be latched, nodes with a subscriber get the new model immediately. Instead of receiving a trigger that they should reload a parameter.

**Comment by rhaschke** [comment]
Closing now. This feature won't merge into ROS1.

**Comment by Timple** [comment]
For future reference: https://github.com/nobleo/rviz_robot_description_topic

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/announcing-rviz-robot-description-topic/42417/1

**Pull request closed without merging**
