### PR TITLE
Allow STL files bigger than expected (printing a warning message).

### PR DESCRIPTION
**Pull request by caguero**
See issue https://github.com/ros-visualization/rviz/issues/945.

### CODE REVIEW

**Comment by wjwwood** [comment]
Thanks @caguero!

@seanyun can you try this to see if it at least loads your STL's? Strictly speaking I think your STL's are not compliant to the STL standard (if I read it correctly).

**Comment by seanyun** [comment]
I'm sorry about the late response. This patch works. I got a bunch of warnings but the graphical model shows up in the right way. Thx!

**Comment by wjwwood** [comment]
Ok, I'll merge this, but I'd still like to know why your models have extra data at the end. Do they open in other tools like Blender and Meshlab?

**Comment by seanyun** [comment]
I can open the STL files in Blender smoothly. I don't see any warning or errors in Blender. 
The STL files were generated by the SolidWorks auto-export.

**Comment by JamesNewton** [comment]
I seem to be having this issue with the attached file. Version 1.12.14.
[LowRes_DexterHDIKinematic_Link1_Bottom.stl.zip](https://github.com/ros-visualization/rviz/files/5079926/LowRes_DexterHDIKinematic_Link1_Bottom.stl.zip)

**Pull request merged**
