### PR TITLE
[Windows][melodic] Fix install destination path.

### PR DESCRIPTION
**Pull request by seanyen-msft**
Follow the catkin guide to place output binaries correctly for cross-platform:
- Place shared libraries like: http://docs.ros.org/api/catkin/html/howto/format2/building_libraries.html
```  
install(TARGETS your_library your_other_library
        ARCHIVE DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
        LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
        RUNTIME DESTINATION ${CATKIN_GLOBAL_BIN_DESTINATION})
```
 
- Place executables like: http://docs.ros.org/api/catkin/html/howto/format2/building_executables.html
```
install(TARGETS your_node
        RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
```

### CODE REVIEW

**Comment by rhaschke** [comment]
Dear @seanyen-msft,
thanks a lot for your effort to bring rviz onto Windows. As you already filed several PRs along this direction (and I assume more will follow), I suggest to collect all those commits on a single development branch and have a single work-in-progress pull-request for it. If the porting is finished, we then can merge all related commits in a single action.
If you agree with this approach, may I ask you to re-organize your existing PRs in this regard?

**Comment by rhaschke** [comment]
I'm not familiar with ROS on Windows. How do you install ROS on Window? Do you follow the approach desribed [here](http://wiki.ros.org/Installation/Windows)?
In order to allow for continuous integration / validation of your Windows porting effort, I suggest to setup https://github.com/marketplace/appveyor.

**Comment by seanyen-msft** [comment]
@rhaschke Did you advice that you will create a staging branch that I can submit PRs toward to? Or I just re-organize everything I have into one single PR but still submitting to `melodic-devel`?

Please excuse me I haven't introduced myself. I am the developer who is working on this project https://aka.ms/ros. And we do have daily CI build already (https://ms-iot.github.io/ROSOnWindows/Build/buildfarm.html) and all the rviz related changes are under https://github.com/ms-iot/rviz/tree/init_windows. Our CI build is referring to a customized [rosdistro](https://github.com/ms-iot/rosdistro-db/tree/init_windows), and for `rviz`, it has been redirected to use `ms-iot\rviz` as the upstream. Our short-term goal is to bring up ROS1 melodic to run natively on Windows and upstream the effort we made to the original repositories. That's why I and @kejxu created so many PRs in many ROS repositories lately. :)

**Comment by rhaschke** [comment]
> Did you advice that you will create a staging branch that I can submit PRs toward to? Or I just re-organize everything I have into one single PR but still submitting to melodic-devel?

I am open to both options, whatever better fits you. The first option allows to accept intermediate commits and thus is slightly easier for the review process. I added a corresponding branch: `wip-windows-port`. Please tell, if you prefer the other option. In this case I will delete the branch again.

Thanks for all the links and introducing yourself and your project. I will have a look later into your CI approach.

**Comment by seanyen-msft** [comment]
@rhaschke Thanks for creating the `wip-windows-port` branch and please keep it. I will be re-sending the PRs to that branch soon.

**Comment by seanyen-msft** [comment]
Closed it since it is moved to #1332

**Comment by seanyen-msft** [comment]
@rhaschke I resent all the existing PRs to the `wip-windows-port` branch. There will be more and will be coming soon. I tried to keep each PR independent enough to only address one issue. Hope that is easier for review.

**Pull request closed without merging**
