### PR TITLE
Add a shortcut key to the Publish Point tool

### PR DESCRIPTION
**Pull request by DaikiMaekawa**

### CODE REVIEW

**Comment by DaikiMaekawa** [comment]
I often use the Publish Point to clean up a Point Cloud data with my private tool. A shortcut key makes me faster to do the same work.
If you think the PR helps others, please merge it.

**Comment by rhaschke** [comment]
The choice of `c` as a short cut for `Publish Point` seems weird.

**Comment by DaikiMaekawa** [comment]
@rhaschke 
OK, then which key do you think the best?
I picked `c` from `click`, and unfortunately `p` is already used for `2D Pose Estimate tool`.

**Comment by beetleskin** [comment]
I like `c`.

**Comment by DaikiMaekawa** [comment]
> Is this automatically merged into melodic-devel?

I guess not. 

@rhaschke Should I open the same PR onto the other distro's branches?

**Comment by rhaschke** [comment]
No need to file a PR for Melodic.

**Pull request merged**
