### PR TITLE
Fix #1120 Visualization markers ignore color and show everything as white

### LINKED ISSUE #1120: Visualization markers ignore color and show everything as white
After the last update on Indigo visualization markers started to appear white.
The message is the same as before and has correct color data.
I suspect it was one of the latest commits about collada file visualization.
Do I understand it correctly that the color information from the Collada file has now higher precedence than the visualization marker message color? If so, what is the reasoning behind that?

### PR DESCRIPTION
**Pull request by xbroquer**
### Description
Fix #1120 Visualization markers ignore color and show everything as white using  #752 as base patch

### Checklist

- Rendering issues:
  - Attached broken rendering image: issue

  - Attached fixed rendering image: mesh_marker_fixed

- Source code snippet for three cases:

// display marker not using mesh material in transparent blue
          marker.color.r = 0;
          marker.color.g = 0;
          marker.color.b = 1;
          marker.color.a = 0.3;
          marker.scale.x = 1;
          marker.scale.y = 1;
          marker.scale.z = 1;
          marker.type = visualization_msgs::Marker::MESH_RESOURCE;
          marker.mesh_resource = "package://my_pkg/moonwalk.dae";
          marker.mesh_use_embedded_materials=false;

// display marker  using mesh material and tinted with transparent green 
        marker.scale.x = 1;
        marker.scale.y = 1;
        marker.scale.z = 1;
        marker.color.r = 0;
        marker.color.g = 1;
        marker.color.b = 0;
        marker.color.a = 0.5f;
        marker.type = visualization_msgs::Marker::MESH_RESOURCE;
        marker.mesh_resource = "package://my_pkg/moonwalk.dae";
        marker.mesh_use_embedded_materials=true;

// display marker  using mesh material and not tinted
        marker.scale.x = 1;
        marker.scale.y = 1;
        marker.scale.z = 1;
        marker.color.r = 0;
        marker.color.g = 0;
        marker.color.b = 0;
        marker.color.a = 0;
        marker.type = visualization_msgs::Marker::MESH_RESOURCE;
        marker.mesh_resource = "package://my_pkg/moonwalk.dae";
        marker.mesh_use_embedded_materials=true;

### CODE REVIEW

**Comment by rhaschke** [comment]
#752 should already part of the source history. Did you have a look into #893 as well, which seems to revert the first one?

**Comment by xbroquer** [comment]
Hi Robert,

Thanks for pointing me #893. Seems that this issue has a long story :)

With rviz melodic release, only external image textures (like PR2 base) are  displayed. When materials are fully defined inside collada file, the mesh is white.

I also used garaemon/rviz_collada_marker fir my tests and added moonwalk marker (that is not using external image files for materials).

The result of rviz melodic release (arrow and moonwalk are white):
Screenshot from 2019-07-22 11-09-00

When mesh_use_embedded_materials=True, color is not dynamically updated

Here is the result with my latest commit:
Screenshot from 2019-07-22 11-08-41

Here the 2 videos that shows the dynamic color update:
[rviz-melodic-collada-test.zip](https://github.com/ros-visualization/rviz/files/3416753/rviz-melodic-collada-test.zip)

However, as you can see, the usage of passes changes the behavior when mesh_use_embedded_materials=True and a color is set. 
The material from the mesh cannot be transparent. If we want the marker transparent we have to set mesh_use_embedded_materials=False (third marker).
**Do you think this behavior change is acceptable ?**

**Comment by rhaschke** [comment]
I don't think that adding a second pass is the right solution to the problem: It essentially just redraws the mesh with the user-defined color. As you see from the comparison, this doesn't allow to change the transparency of the mesh.
Another option is to use alpha from the user-defined color for both passes, and use the second pass to tint the mesh with the user-defined color as suggested in this PR. However, this will also modify the result for texture-colored meshes.
I think, we need to modify the color "towards" the user-defined one in first place. A single pass will suffice then for drawing. One option is to multiply with the user-defined color.

 multiply | current rviz | pull request 
-----------|-----------|--------
mesh-multiply | mesh-original | mesh-pr

**Comment by rhaschke** [comment]
Closing in favor of #1424. @xbroquer, could you please review the new PR?

**Pull request closed without merging**
