### PR TITLE
Update display if empty pointcloud2 is published

### PR DESCRIPTION
**Pull request by axelschroth**
Currently, a PointCloud2 display keeps showing the old point cloud if an empty point cloud message is published. I consider this a bug, since rviz still shows old data which is invalid in the meantime.

### CODE REVIEW

**Comment by wjwwood** [comment]
Thanks for the report and pr, I'll investigate it asap. If you have time to provide it, a simple bag file that reproduces the problem would make it easier for me to test this.

As you can imagine, this is sensitive code (a break in this code would affect a lot of users), so I'll have to be quite cautious with it. If any other point cloud users can +1/-1 this I would appreciate it too.

**Comment by axelschroth** [comment]
Sure, attached you will find a bag publishing some points on /point_cloud followed by an empty point cloud.

[test_pointcloud_2017-01-10-10-20-10.bag.zip](https://github.com/ros-visualization/rviz/files/695730/test_pointcloud_2017-01-10-10-20-10.bag.zip)

**Comment by wjwwood** [comment]
Sorry it took me so long to get back to you. I've reproduced what you've described and that your patch fixes it. Thanks for giving a clear description and a reproducible bag, makes my job a lot easier :smile:!

I'll still do a code review before merging, but it's looking good so far.

**Comment by wjwwood** [comment]
Backported in https://github.com/ros-visualization/rviz/pull/1110

**Pull request merged**
