### PR TITLE
Add missing include

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Review by rhaschke — COMMENTED** [review]
I don't yet see why this header requires ros/console.h. Could you please explain?

**Comment by jspricke** [comment]
Because the header uses `ROS_ERROR`

**Review by rhaschke — APPROVED** [review]
Thanks for the clarification.

**Comment by rhaschke** [comment]
Merged into [Melodic](https://github.com/ros-visualization/rviz/commit/554d032e554cfcfda3d1233ef0f385dc8475ae59) and from there into [Noetic](https://github.com/ros-visualization/rviz/commit/d8df909abe87899f66d1bf9471cfeb27395c4186).

**Pull request closed without merging**
