### PR TITLE
Fix #879

### LINKED ISSUE #879: Angular torque marker is dettached with negative z-axis torque
Originally reported in https://github.com/tork-a/dynpick_driver/issues/16.

img1
img2

To reproduce,
```
term-1$ rosrun rviz rviz   (then choose `base` as the fixed frame, and open Wrench plugin on RViz, choose "`/force`" topic)

term-2$ rosrun tf static_transform_publisher 0.0.0 0.0 0.0 0.0 0.0 2.0 /base /sensor 100

term-3$ rostopic pub -r 10 /force geometry_msgs/WrenchStamped '{ header: { seq: 1, stamp: 11, frame_id: "base" }, wrench: { force: { x: 0.5, y: 0.5, z: 1.0 }, torque: { x: 0.5, y: 0.5, z: -1.1 } } }'
```

```
$ dpkg -p ros-indigo-rviz|grep Vers
Version: 1.11.7-0trusty-20150328-2254-+0000
```
But another user reported that this happens on Hydro too.

### PR DESCRIPTION
**Pull request by goretkin**
Sorry to pull against groovy. Should forward-port cleanly.

### CODE REVIEW

**Comment by wjwwood** [comment]
#879

**Comment by 130s** [comment]
I tried this PR on Indigo by just rebasing to `origin/indigo-devel`, and I still see the same issue happening unfortunately.

**Comment by 130s** [comment]
rviz_wrench_off_gorekin

**Comment by goretkin** [comment]
Can you confirm that you're running the recompiled binary? by doing
something like adding a print statement.

**Comment by 130s** [comment]
@goretkin yeah, I removed rviz by `sudo apt-get remove ros-indigo-rviz` and `rospack find rviz` points to the source directory.

**Comment by goretkin** [comment]
I suppose I can only confirm the fix on groovy (it works for me), but it does seem bizarre that it's not working for you on Indigo.

Could you try to change the line
```cpp
Ogre::Quaternion orientation = axis_z.getRotationTo(torque);
``` 

to 
```cpp
Ogre::Quaternion orientation = axis_z.getRotationTo(axis_z);
```

This should make the orientation of the torque circle marker be at a fixed orientation. For example the yellow and purple arrows below are torque vectors, but their circular markers are oriented in a fixed way.

intentionally_detached_torque

**Comment by 130s** [comment]
+1

It seems to be working on my Indigo as well. I just had to uninstall RViz deb.
rviz_issue879_pr2
rviz_issue879_pr1

**Comment by goretkin** [comment]
@130s, sorry I don't understand. What is working? What do those screenshots correspond to?

**Comment by 130s** [comment]
Sorry my last post wasn't clear. 

Your pull request works on my Indigo, without any additional modification that you suggested. 
Earlier I reported that your PR still didn't solve the issue, which turned out that I was still referencing to the RViz installed via apt.

**Comment by goretkin** [comment]
@130s , I'm glad to hear it. The "additional modification" was not a fix, but was a confirmation that you were actually running the RViz you compiled. Looks like you weren't, but you figured it out another way.

The screenshots you included, just to confirm, show the broken behavior, right?

**Comment by wjwwood** [comment]
Ok, I'll merge and then forward port this to hydro and indigo/jade.

**Comment by wjwwood** [comment]
Hydro forward port: https://github.com/ros-visualization/rviz/pull/902

**Comment by wjwwood** [comment]
Indigo forward port: https://github.com/ros-visualization/rviz/pull/903

**Comment by goretkin** [comment]
Thanks!

**Pull request merged**
