### PR TITLE
Adding option to transform map based on header timestamp

### PR DESCRIPTION
**Pull request by ayrton04**
Addresses #1065. Wasn't sure what name to give the property in the display window. I'm open to suggestions if anyone has any!

### CODE REVIEW

**Comment by NikolausDemmel** [comment]
LGTM.

The name is reasonable IMHO.

**Comment by wjwwood** [comment]
Cool, I'll try it out locally ASAP. @ayrton04 can you give an example scenario where I could test this out?

**Comment by ayrton04** [comment]
I'm afraid I don't have code I can share, but if you turn a delayed laser scan into an occupancy grid with a timestamp and `frame_id` of the laser scan itself, then it becomes easy to see the effect of the PR.

**Comment by ayrton04** [comment]
I've also found that just running a robot in sim and visualizing the local costmap works well. If it moves around a fair amount when the new parameter is set to false, it becomes much more stable after enabling it.

**Comment by wjwwood** [comment]
I tried using the examples in `navigation_stage` but I was unable to see the change you're talking about when enabling/disabling this option. Maybe you could make a short video/gif and upload it?

**Comment by ayrton04** [comment]
Sure, I'll do that.

**Comment by wjwwood** [comment]
I tried this again but I still couldn't see the difference. I must be doing something that doesn't exhibit the problem in the first place. Since the code lgtm and its hidden behind an option with a default behavior that hasn't changed, I'm going to go ahead and merge this. If someone else notices this doesn't resolve the problem we can fix it up then.

**Comment by ayrton04** [comment]
Apologies, @wjwwood. I am running Xenial/Kinetic, and was hoping to use one of the open-source robot sims to produce an example, but never found a Kinetic-friendly one, and didn't get around to building an Indigo install in Xenial.

**Pull request merged**
