### PR TITLE
OgreVector3.h is deprecated in favor of OgreVector.h

### PR DESCRIPTION
**Pull request by lucasw**
### Description

Replace all includes of OgreVector3.h with OgreVector.h for Ogre 1.12 (I noticed this because locus Fuse has Werror and errored on the OgreVector3.h with ogre 1.12).

### Checklist

- [ ] If you are addressing rendering issues, please provide:
  - [ ] Images of both, broken and fixed renderings.
  - [ ] Source code to reproduce the issue, e.g. a `YAML` or `rosbag` file with a `MarkerArray` msg.
- [ ] If you are changing GUI, please include screenshots showing how things looked *before* and *after*.
- [ ] Choose the proper target branch: latest release branch, for non-ABI-breaking changes, *future* release branch otherwise.
      Due to the lack of active maintainers, we cannot provide support for older release branches anymore.
- [ ] Did you change how RViz works? Added new functionality? Do not forget to update the tutorials and/or documentation on the [ROS wiki](http://wiki.ros.org/rviz)
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-visualization/rviz/pulls) to support the maintainers of RViz. Refer to the [RViz Wiki](https://github.com/ros-visualization/rviz/wiki/Maintainer-Guide#reviewing-pull-requests) for reviewing guidelines.

### CODE REVIEW

**Comment by rhaschke** [comment]
Replacing `OgreVector3.h` with more generic `Ogre.h` isn't a good way to go: this requires including many more files, which slows down compilation. In Ogre 1.12, there is `OgreVector.h` (without 3), but this is not available in earlier versions...

**Comment by lucasw** [comment]
It looks like it takes around 24 minutes instead of 20 in the ci system, assuming the ci is consistent.

What do you think of this intermediary include with an ogre version conditional include in it?

**Comment by rhaschke** [comment]
Using conditional includes is fine. What kind of deprecation warnings do you get? From which source file?

**Comment by lucasw** [comment]
```
In file included from /home/lucasw/base_catkin_ws/src/ros/rviz/src/rviz/robot/robot_link.h:40,
                 from /home/lucasw/base_catkin_ws/src/ros/rviz/src/rviz/robot/robot_joint.cpp:31:
/usr/include/OGRE/OgreVector3.h:2:62: note: ‘#pragma message: /usr/include/OGRE/OgreVector3.h is deprecated, migrate to Ogre.h’
    2 | #pragma message( __FILE__ " is deprecated, migrate to Ogre.h")
```

**Comment by rhaschke** [comment]
I added a CI build job for OGRE 1.12. Please rebase your branch onto latest noetic-devel to see remaining issues. Thanks.

**Review by rhaschke — APPROVED** [review]
Looks good to me. I don't see a warning about OgreVector3.h anymore. Do you?

**Comment by lucasw** [comment]
Nope, just a bunch of the `deprecated-copy` warnings on the jenkins focal build- but that must be failing everywhere, not related to this

**Pull request merged**
