### PR TITLE
add option to disable keyboard focus being set on mouse move

### PR DESCRIPTION
**Pull request by simonschmeisser**
currently all mouse events get forwarded to onRenderWindowMouseEvents,
there keyboard focus is requested (setFocus) unconditionally. This commit
adds a new property "focus_on_mouse_move_" that enables setting keyboard
focus on mouse move events. Setting focus on click or wheel is handled by
QObject::setFocusPolicy

Subclasses/Users of rvis::RenderPanel can disable either setting focus on
mouse move by using the boolean property and disable keyboard focus on click,
on wheel or totally via setFocusPolicy

### CODE REVIEW

**Comment by simonschmeisser** [comment]
ping?

**Comment by dhood** [comment]
thanks for the PR, we'll take a look at it as soon as possible

**Comment by wjwwood** [comment]
@simonschmeisser if you want/need this in `kinetic-devel` then we'll have to find a way to do it ABI compatible. Feel free to start a discussion about that if you want after I merge this. Thanks for pr!

**Comment by simonschmeisser** [comment]
@wjwwood thanks for merging it to melodic. I'm fine that way. We will upgrade asap anyway and have a workaround for the time being

**Pull request merged**
