### PR TITLE
generalize WrenchVisual

### PR DESCRIPTION
**Pull request by rhaschke**
This PR attempts to increase code-reusability for `rviz::WrenchStampedVisual`, which is currently used by the wrench display plugin.
The visual itself doesn't handle or use the timestamp. Hence I suggest to:
- change the API of `setMessage()` to accept a `geometry_msgs::Wrench` 1c341c0
- rename `setMessage()` to `setWrench()` 1c341c0
- add an additional method `setWrench(Vector3 force, Vector3 torque)` 24e4bab

Furthermore, I modified the code to allow for
- hiding the markers e78ebee
- auto-hiding the force or torque marker if their magnitude becomes too small (which created strange artifacts in existing code) 7a51333

### CODE REVIEW

**Comment by wjwwood** [comment]
@rhaschke I'll have to consider this for Kinetic-only. I think there's a good change others are already using the API as-is in Indigo/Jade.

**Comment by rhaschke** [comment]
@wjwwood Targeting kinetic is fine. To maintain API stability, I can add the original setMessage() function, which would be a simple wrapper then. 
If you agree to this idea, I could prepare an API-compatible version targeted to indigo, depreacating the critical API functions for later removal in kinetic?

**Comment by wjwwood** [comment]
@rhaschke that would work fine. I would consider releasing for Indigo if this only added to the current API.

**Comment by rhaschke** [comment]
@wjwwood I fixed my changes to retain API and ABI compatibility.
If you have merged this into Indigo, I will create another PR for Kinetic, merging and cleaning up this, i.e. removing the deprecated function and renaming the class WrenchStampedVisual to WrenchVisual.

**Comment by wjwwood** [comment]
lgtm, I'm going to squash it somehow.

**Pull request merged**
