### PR TITLE
change the default ambient color to 0's

### PR DESCRIPTION
**Pull request by wjwwood**
Addresses issue #836

Before:

screen shot 2015-01-18 at 9 29 23 pm

After:

screen shot 2015-01-18 at 9 21 57 pm

### CODE REVIEW

**Comment by wjwwood** [comment]
For comparison, the rendering from `Preview.app`:

screen shot 2015-01-18 at 10 27 03 pm

**Comment by wjwwood** [comment]
@hersh Do you know of any issues with using all `0`'s for the RGB ambient values? I've seen other places in ROS code where very small values are used instead, but I don't get why that is the case.

**Comment by wjwwood** [comment]
I discussed this with some Gazebo people and it also renders fine. I'm gonna merge it for now.

**Comment by gavanderhoorn** [comment]
@wjwwood: this probably won't be backported to Hydro?

**Comment by wjwwood** [comment]
@gavanderhoorn I wasn't planning on it, but if it does ok in Indigo, I would consider a pull request that back ported it to hydro.

**Pull request merged**
