### PR TITLE
Enhancement: Add pose covariance displays

### PR DESCRIPTION
**Pull request by Ellon**
Hi all,

This PR addresses #381 .

I've been working on visualizing properly the covariances on rviz, improving what was done on [rviz_plugin_covariance](https://github.com/laas/rviz_plugin_covariance). I decided to integrate it already on rviz so other people could discuss the enhancements here.

Summary of features:
- New CovarianceProperty class to hold all properties related to covariances
- New CovarianceVisual class to perform the drawing of the covariances
- New PoseWithCovariance display for PoseWithCovarianceStamped messages
  - Selection tool is working properly
  - Covariance can be hidden if needed
- Update Odometry display to show covariances
  - Odometry can be visualized as Axes or Arrow (idea borrowed from PoseDisplay)
  - Shape related options grouped under shape property
  - Covariance can be hidden if needed
- Add test script for messages with covariances

Future features:
- Add proper visualization of orientation covariance. Currently it's just a cone with the same logic of the position covariance, and it's not at all intuitive. I plan to add something like the figure 2 of [this article](http://groups.csail.mit.edu/rrg/papers/icra12_aggressive_flight.pdf) that I found on [this email exchange](http://ros-users.122217.n3.nabble.com/Announcing-rviz-plugin-covariance-td4018674.html) on ros-users.

More information can be found in the discussions [here](https://github.com/laas/rviz_plugin_covariance/issues/10) and [here](https://github.com/laas/rviz_plugin_covariance/pull/11).

### CODE REVIEW

**Comment by wjwwood** [comment]
Thanks for the pr. As I mentioned here: https://github.com/laas/rviz_plugin_covariance/pull/11 I'd like to see the plugin merged and fixed up over there first. If people agree it is working well then I'll consider it for integration into rviz.

**Comment by NikolausDemmel** [comment]
+1 for getting this into rviz. I guess there cannot be too many serious users out there that we would "leave behind". And it is not too hard to switch your rviz config to use the new plugin from rviz proper. We could add deprecation warning to the plugin in the extra repo, informing users about a more up-to-date version in rviz.

In particular before the latest PR was merged in the plugin repository, the reference frames in which the covariances were displayed were wrong. Therefore that was a breaking change in any case (either fixing previously wrong displays, or breaking workarounds for the previously wrong displays).

**Comment by jihoonl** [comment]
+1 for this.

**Comment by corot** [comment]
:+1: I have been using it for a month and works fine

**Comment by corot** [comment]
Hi @Ellon, did you consider remake this PR for Kinetic?

**Comment by Ellon** [comment]
HI @corot, no I didn't considered it. In my developments here I'm using Indigo, and I don't have time now to this remake right now. Maybe soon in the future. But feel free to propose a remake if you have time to do so!

**Comment by wjwwood** [comment]
Closing in favor of https://github.com/ros-visualization/rviz/pull/1096

**Pull request closed without merging**
