### PR TITLE
Enable/Disable hotkeys

### PR DESCRIPTION
**Pull request by rhaschke**
This is a rework of #1243. @AndyZe, please review.

### CODE REVIEW

**Comment by rhaschke** [comment]
@AndyZe, while I guess this PR is ready for merging, I'm not yet convinced that we really need this feature. As an alternative, you can always disable (i.e. remove) individual tools. I would consider this a much more flexible approach than disabling all tool hotkeys. Did you considered such an option?

**Comment by AndyZe** [comment]
Well, I didn't think of that. That does work, if people are aware of that option.

Is there any harm in merging this?

**Comment by AndyZe** [comment]
I don't have a strong opinion. Like I said, my motivating issue was resolved a long time ago.

**Comment by AndyZe** [comment]
I will say, most well-polished apps don't have single-character hotkeys. It's usually "Ctrl+something"...

**Comment by rhaschke** [comment]
I don't think disabling all hotkeys is the right approach to disable a single specific tool.
We should strive for a more general solution, allowing to define custom hotkeys.

**Pull request closed without merging**
