### PR TITLE
feat: Configurable tool button style melodic

### PR DESCRIPTION
**Pull request by reinzor**
Same as #1307 for melodic

### CODE REVIEW

**Comment by reinzor** [comment]
Can this one be merged as well?

**Comment by reinzor** [comment]
ping

**Comment by reinzor** [comment]
Can this one be merged as well? It is already merged in the kinetic branch ..

**Comment by wjwwood** [comment]
Normally we do forward porting ourselves, unless there's significant changes required to forward port (normally we request pr's to the latest release branch instead and do backports, but didn't in this case).

We do forward and back porting when we release, so this will get addressed then if not before. I cannot say right now when we'll do the next release though.

In the meantime, maybe @chapulina has time to review and merge this one too since she did the original one as well.

**Comment by chapulina** [comment]
This is on my radar together with lots of other things. I'll try to get to it next week. :crossed_fingers:

**Comment by reinzor** [comment]
Okay, thanks for the update :)

**Pull request merged**
