### PR TITLE
Ellon feature/covariances  kinetic devel

### PR DESCRIPTION
**Pull request by wjwwood**
Replacement for https://github.com/ros-visualization/rviz/pull/974

### CODE REVIEW

**Comment by wjwwood** [comment]
@Ellon I need you to copyright and license your newly added files for this pr. The easiest thing to do is put it under the same license. If you're fine with that, please make a pr against this branch which copies the copyright/license stanza from one of the other files and replace the copyright (probably for WillowGarage) with your own copyright.

Thanks!

**Comment by wjwwood** [comment]
For a few files you copied the stanza, but left Willow Garage as the copyright holder, please replace that with yourself or your company/school if that's appropriate.

**Comment by Ellon** [comment]
Hey @wjwwood, I updated the licenses in #1097 . Is that OK for you? I also think we should wait for a feedback from @thomas-moulard, since he was the original author of the plugin, and his files didn't contained copyright/license.

Btw, I developed a little bit more the plugin. I have the commits in my personal repo. Should I take the opportunity and add these modifications here?

**Comment by thomas-moulard** [comment]
@Ellon Adding those copyright header is OK, thanks!

**Comment by wjwwood** [comment]
Thanks guys, I need to release rviz again since there is a regression for some systems, so I'll get this in too.

**Comment by Ellon** [comment]
By "this" you mean this merge here, or the other stuff i mentioned?

**Comment by wjwwood** [comment]
I didn't see the this, edits don't send notifications. Yes. If you've updated the plugin it would be good to get those changes into rviz.

**Comment by Ellon** [comment]
Done in #1099

**Pull request merged**
