### PR TITLE
Fixed duplicate property name for Path colors

### PR DESCRIPTION
**Pull request by hiddewie**
See issue #1087.

### CODE REVIEW

**Comment by romainreignier** [comment]
Successfully tested!
Thanks @hiddewie !
:+1:

**Comment by wjwwood** [comment]
Thanks for the fix!

Looks like the duplicate property name was introduced in this pr: https://github.com/ros-visualization/rviz/pull/1016 and then forward ported to kinetic-devel by me. Since this is a relatively new feature that caused a bug I'll take this pr now. Otherwise I'd have been cautious of changing a property name because it might break existing config files.

I'll mark this for back port to indigo/jade as well. Thanks again!

**Comment by romainreignier** [comment]
Will it be part of the next Kinetic sync? It would be great.

**Comment by wjwwood** [comment]
Backported in https://github.com/ros-visualization/rviz/pull/1110

**Pull request merged**
