### PR TITLE
Fix #911 #616 : TF Segfaults on reset/update

### LINKED ISSUE #808: TF display segfault (openni_tracker related)
I'm attempting to play a bag file captured from `openni_tracker` (skeleton tracking using the kinect), with an additional (custom) frame meant to provide a global reference. The custom frame is produced using a static transform publisher started in the launch file. During playback, RViz crashes if the TF plugin is loaded. If I don't load the TF plugin, RViz is fine; other nodes I'm running that do transforms between `global` and other frames also seem happy.

The crash can be reproduced by launching the following (note that I left `gdb` in there):
```
<launch>
  <param name="use_sim_time" type="bool" value="true" />
  <node pkg="tf" type="static_transform_publisher" name="depth_2_global" args="3.0 0.25 0 0 0 0 /global /camera_link 100"/>
  <node pkg="rviz" name="rviz" type="rviz" output="screen" launch-prefix="gdb -ex run --args" args="-d tf_debug.rviz" />
</launch>
```
then playing a bag file that recorded the `/tf` topic produced by `openni_tracker`:
```
rosbag play --clock skeleton.bag
```
I'm not sure I got the static transform correct, which is why I was attempting to view the TF frames. Since I can't post the bag file and the `.rviz` file is a bit unwieldy, all three files (`gdb_rviz.launch`, `skeleton.bag.tar.gz`, and `tf_debug.rviz`) are available at: https://personal.traclabs.com/~jkramer3/.

The crash happens about 8 seconds in, with the following gdb backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff7b03221 in rviz::Property::Property(QString const&, QVariant, QString const&, rviz::Property*, char const*, QObject*) () from /opt/ros/hydro/lib/librviz.so
#2  0x00007fffb03d64f2 in rviz::TFDisplay::updateFrame(rviz::FrameInfo*) ()
   from /opt/ros/hydro/lib/libdefault_plugin.so
#3  0x00007fffb03d8189 in rviz::TFDisplay::createFrame(std::string const&) ()
   from /opt/ros/hydro/lib/libdefault_plugin.so
#4  0x00007fffb03d875e in rviz::TFDisplay::updateFrames() () from /opt/ros/hydro/lib/libdefault_plugin.so
#5  0x00007fffb03d8826 in rviz::TFDisplay::update(float, float) () from /opt/ros/hydro/lib/libdefault_plugin.so
#6  0x00007ffff7aa4a91 in rviz::DisplayGroup::update(float, float) () from /opt/ros/hydro/lib/librviz.so
#7  0x00007ffff7b53749 in rviz::VisualizationManager::onUpdate() () from /opt/ros/hydro/lib/librviz.so
#8  0x00007ffff2c17281 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#9  0x00007ffff2c1c179 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#10 0x00007ffff6ec7894 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#11 0x00007ffff6ecc713 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#12 0x00007ffff2c02e9c in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#13 0x00007ffff2c341f2 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#14 0x00007ffff2c31c0d in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#15 0x00007ffff1987d13 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff1988060 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff1988124 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff2c32426 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#19 0x00007ffff6f6fd9e in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#20 0x00007ffff2c01c82 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#21 0x00007ffff2c01ed7 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#22 0x00007ffff2c06f67 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#23 0x0000000000400b0c in main ()
```
I'm running hydro on Ubuntu 12.04, everything up to date as of today.

### LINKED ISSUE #911: Rviz crashes when started with specific tf but not others
I'm playing back a bag with a occupancy_grid, pointclouds, and a tf system. If the fixed frame is set to a specific (which happens to be the root of the tf tree) rviz will crash the moment bag playback starts. If the fixed frame is set to any other frame in the bag the playback will work correctly. After the first set of messages are displayed you can set the fixed frame to any other frame and rviz is fine. It doesn't matter how far into the bag I start playback the same thing happens. I've only included the gdb backtrace but I can include everything rviz prints on startup (its a lot of text) if desired.

```
**GDB Backtrace**
[ INFO] [1440030397.386498288, 1438292950.921057766] [/playback_rviz]: Font Arial using texture size 512x512
[ INFO] [1440030397.388154812, 1438292950.921564215] [/playback_rviz]: Info: Freetype returned null for character 160 in font Arial
[ INFO] [1440030397.388429254, 1438292950.921564215] [/playback_rviz]: Texture: ArialTexture: Loading 1 faces(PF_BYTE_LA,512x512x1) with 0 generated mipmaps from Image. Internal format is PF_BYTE_LA,512x512x1.
[ INFO] [1440030400.943647025, 1438292951.276780689] [/playback_rviz]: Texture: MapTexture0: Loading 1 faces(PF_L8,3072x3072x1) with 0 generated mipmaps from Image. Internal format is PF_L8,3072x3072x1.

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) 
(gdb) backtrace
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff7affd01 in rviz::Property::Property(QString const&, QVariant, QString const&, rviz::Property*, char const*, QObject*) ()
   from /opt/ros/indigo/lib/librviz.so
#2  0x00007fff953edeae in rviz::TFDisplay::updateFrame(rviz::FrameInfo*) ()
   from /opt/ros/indigo/lib/libdefault_plugin.so
#3  0x00007fff953ef4d7 in rviz::TFDisplay::updateFrames() ()
   from /opt/ros/indigo/lib/libdefault_plugin.so
#4  0x00007fff953ef756 in rviz::TFDisplay::update(float, float) ()
   from /opt/ros/indigo/lib/libdefault_plugin.so
#5  0x00007ffff7aa7692 in rviz::DisplayGroup::update(float, float) ()
   from /opt/ros/indigo/lib/librviz.so
#6  0x00007ffff7b48bbe in rviz::VisualizationManager::onUpdate() ()
   from /opt/ros/indigo/lib/librviz.so
#7  0x00007ffff2e2387a in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#8  0x00007ffff2e27a31 in QObject::event(QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#9  0x00007ffff6edce2c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#10 0x00007ffff6ee34a0 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#11 0x00007ffff2e0f4dd in QCoreApplication::notifyInternal(QObject*, QEvent*)
---Type <return> to continue, or q <return> to quit---
    () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#12 0x00007ffff2e3f323 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#13 0x00007ffff2e3c629 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#14 0x00007ffff1782e04 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff1783048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff17830ec in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff2e3c7a1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#18 0x00007ffff6f7ebe6 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#19 0x00007ffff2e0e0af in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#20 0x00007ffff2e0e3a5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#21 0x00007ffff2e13b79 in QCoreApplication::exec() ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#22 0x0000000000400bc7 in main ()
```

### PR DESCRIPTION
**Pull request by arntanguy**
Do not needlessly delete tree_property_ elements, update them instead.
See #911 for details.

Most likely fixes #808 too.

### CODE REVIEW

**Comment by wjwwood** [comment]
Thanks, I'll try to give it a review asap.

@CaffeineSqurr if you have any time I'd appreciate it if you could try this patch against your original issue. I'll try to do it as well, but it might be a little while until I can.

@jkramer3 or @OkkeHendriks can either of you test your use cases from #808 against this patch?

**Comment by wjwwood** [comment]
The changes look ok to me, since we're not currently passing the last two optional parameters to the constructor of `Property` there doesn't appear to be any side effects of the constructor that we'd be missing.

I still have to test it out.

**Comment by wjwwood** [comment]
Ok, I can reproduce #808 and I can see that this patch improves that case.

**Comment by arntanguy** [comment]
Thanks for the quick reaction.
Now that this is fixed, I'll look into #834 as soon as I have time.

**Pull request merged**
