### PR TITLE
Try fix #1711

### LINKED ISSUE #1711: RoboStack build broken for MacOS
@wolfv, see https://github.com/ros-visualization/rviz/runs/5085111018?check_suite_focus=true

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Add missing robostack-experimental channel to fix #1711

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Needs https://github.com/conda-forge/rosdep-feedstock/pull/18

**Comment by wolfv** [comment]
@Tobias-Fischer we might not need this as we have `pyqt-builder` in conda-forge now: https://github.com/conda-forge/pyqt-builder-feedstock

**Comment by rhaschke** [comment]
The problem still persists.

**Comment by Tobias-Fischer** [comment]
We found the source of the issue - the robostack internal mapping has changed. I'm chatting with @wolfv to see what his preference is to fix it. https://github.com/conda-forge/rosdep-feedstock/pull/18 is one way, the other is to revert back to the old mapping.

**Comment by rhaschke** [comment]
Thanks for the info. I will wait for your final decision.

**Comment by Tobias-Fischer** [comment]
Ping @wolfv

**Comment by rhaschke** [comment]
Closing due to inactivity.

**Pull request closed without merging**
