### PR TITLE
fix initial pose and goal buttons

### PR DESCRIPTION
**Pull request by doisyg**
Fix https://github.com/ros-visualization/rviz/issues/1509#
The wrong TF2 conversion was used

### CODE REVIEW

**Comment by rhaschke** [comment]
Can you explain a little bit more, what is wrong with `tf2::convert`? Shouldn't that work as well?

**Comment by doisyg** [comment]
http://docs.ros.org/noetic/api/tf2/html/namespacetf2.html#af1255c37833c838543b512febce5e9b1
http://wiki.ros.org/tf2/Tutorials/Quaternions

```
void tf2::convert ( const A &  a,  B & b ) 
a | an object to convert from
b | the object to convert to
```

a and b were inverted, `quat_msg = tf2::toMsg(quat_tf)` does the same and has the advantage of being less ambiguous

**Comment by doisyg** [comment]
But I will happily fix it using convert the other way around if preferred

**Comment by rhaschke** [comment]
I see. Thanks for clarification.
There might be other places in the rviz code base using `tf2::convert` in the wrong order. It would be great, if you could check (and fix) them as well. I prefer the less ambiguous `toMsg()` / `fromMsg()` too. Thanks for your help!

**Comment by doisyg** [comment]
`tf2::convert` is also used in https://github.com/ros-visualization/rviz/blob/noetic-devel/src/test/rviz_logo_marker.cpp and https://github.com/ros-visualization/rviz/blob/noetic-devel/src/test/marker_test.cpp, but properly I believe

**Comment by rhaschke** [comment]
Just to improve readability / reduce ambiguity, I would appreciate it if you could replace those instances as well.

**Comment by doisyg** [comment]
Done

**Comment by rhaschke** [comment]
Could you please fix the clang-format issues indicated by Travis yourself here?

**Pull request merged**
