### PR TITLE
load_config and save_config services (Noetic)

### PR DESCRIPTION
**Pull request by RobertBlakeAnderson**
Update of #1199 , changing the fork branch to melodic-devel. Reviewer comments incorporated as well.

### CODE REVIEW

**Comment by danem** [comment]
Any progress on this? I'd like this feature as well.

**Comment by RobertBlakeAnderson** [comment]
I'm ready to update this if the maintainers indicate they're willing to merge it.

**Comment by rhaschke** [comment]
Sorry, I wasn't even looking at old, but failing PRs. However, looks like CI failed for an unrelated reason. Could you please rebase onto noetic-devel (as this introduces ABI changes) and resolve conflicts?

**Comment by RobertBlakeAnderson** [comment]
Looks like it's ready to go now.

**Comment by rhaschke** [comment]
Hi @RobertBlakeAnderson,

I slightly adapted your code, namely moved the services into VisualizerApp, which should only be used by the rviz binary. There is also the only other service provided by rviz. I also reverted the introduction of the load helper. I think loading should support the same features as on the commandline, e.g. loading from "shortcut names".

However, I cannot test this, because ROS cannot find the service message:

```
$ rosservice info /rviz_idas_1371_4556839036678344986/load_config 
Node: /rviz_idas_1371_4556839036678344986
URI: rosrpc://idas:39093
Type: rviz/SendFilePath
ERROR: Unable to load type [rviz/SendFilePath].
Have you typed 'make' in [rviz]?
```
However, when requesting the message info, I get a valid result. Looks like I have some more basic issue with ROS, maybe because I'm using ROS testing? Need to test on another system...
```
$ rossrv show rviz/SendFilePath 
std_msgs/String path
  string data
---
bool success
```
Could you have a final look as well?

**Comment by rhaschke** [comment]
I figured out the issue: rviz' python bindings are shadowing the rviz python module created by the message generation system, such that `rviz.srv` cannot be loaded as a module.
I guess, you tested this via a C++ interface only?

I will merge this tomorrow as is into Melodic (because I removed ABI incompatibilities) and fix the python API for the services in a Noetic fixup.

**Comment by rhaschke** [comment]
Merged via #1492.

**Pull request closed without merging**
